name: check

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:master

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: make lint

  schemas:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:master

    steps:
    - uses: actions/checkout@v3
    - run: make schemas

  locales:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:master

    steps:
    - uses: actions/checkout@v3
    - run: echo "::add-matcher::.github/problem-matchers/gettext.json"
    - run: make locales

  gtk-builder-validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:master

    steps:
    - uses: actions/checkout@v3
    - run: xvfb-run make gtk-builder-validate

  msgcmp:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:master

    steps:
    - uses: actions/checkout@v3
    - run: echo "::add-matcher::.github/problem-matchers/gettext.json"
    - run: make msgcmp

  test:
    concurrency: ${{ github.sha }}/${{ github.workflow }}/test/${{ matrix.image }}/${{ matrix.session }}

    needs:
    - lint
    - schemas
    - locales
    - gtk-builder-validate
    - msgcmp

    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/ddterm/ci-docker-image:master
      options: --privileged --cgroupns=host --tmpfs /tmp --tmpfs /run

    strategy:
      fail-fast: false
      matrix:
        image:
          - 'fedora-35'
          - 'fedora-36'
          - 'debian-11'
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
        session:
          - 'TestXSession'
          - 'TestWayland'
          - 'TestWaylandHighDpi'
          - 'TestWaylandDualMonitor'

    env:
      IMAGE: ghcr.io/ddterm/gnome-shell-pod/${{ matrix.image }}:master
      PY_COLORS: 1
      TOX_TESTENV_PASSENV: PY_COLORS GITHUB_ACTIONS
      TOXENV: py3-ghactions

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{ github.repository_owner }}

    - id: cached_result
      uses: amezin/action-download-artifact@ea2ac00d352664b46e58f50b2fcdefffa4e94758
      with:
        commit: ${{ github.sha }}
        name: ${{ matrix.session }}-${{ matrix.image }}
        path: test
        fail_if_not_found: false

    - run: npm ci
      if: ${{ success() && steps.cached_result.outputs.found != 'true' }}

    - run: xvfb-run make test-deps
      if: ${{ success() && steps.cached_result.outputs.found != 'true' }}

    - run: tox -vv --notest --sitepackages
      working-directory: test
      if: ${{ success() && steps.cached_result.outputs.found != 'true' }}

    - run: for retry in 1 2 3; do podman pull "${{ env.IMAGE }}" && break; done
      if: ${{ success() && steps.cached_result.outputs.found != 'true' }}

    - run: tox --sitepackages -- --self-contained-html --junitxml=junit.xml --container-image "${{ env.IMAGE }}" -n 2 --screenshot-failing-only -v "test_extension.py::${{ matrix.session }}"
      working-directory: test
      if: ${{ success() && steps.cached_result.outputs.found != 'true' }}

    - run: testspace --verbose "[${{ matrix.image }}]./test/junit.xml" "[${{ matrix.image }}/test_extension.${{ matrix.session }}]+./test/report.html"
      if: always()

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.session }}-${{ matrix.image }}
        path: |
          test/report.html
          test/junit.xml
      if: ${{ steps.cached_result.outputs.found != 'true' }}
